/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizadorlexico;

import javax.swing.JOptionPane;

/**
 *
 * @author WillOP
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("Cajadetexto"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // primero acceder al texto de textarea
        char[] texto = jTextArea1.getText().toCharArray();
        int tamanio = texto.length;
        int estado = 0;
        int errores=0;
        
        for (int contador = 0; contador < tamanio; contador++) {
            //estado 0
            switch (estado) {
                // estado 0
                case 0:
                    //comentarios
                    if(texto[contador]== 47 ){
                        estado=1;
                    }
                    //verificar si es una palabra
                    else if(Character.isLetter(texto[contador])){
                        estado = 3;
                    }
                    //verificar si es un numero
                    else if(Character.isDigit(texto[contador])){
                        estado = 4;
                    }
                    //validar simbolos validos = ; (  ) {  } y "asdfas"
                    else if(texto[contador]== 9){
                        estado=0;
                    }
                    else if(texto[contador]== 32){
                        estado=0;
                    }
                    else if(texto[contador]== 10){
                        estado=0;
                    }
                    else if(texto[contador]== 61){
                        estado=0;
                    }
                    else if(texto[contador]== 59){
                        estado=0;
                    }
                    else if(texto[contador]== 40){
                        estado=0;
                    }
                    else if(texto[contador]== 41){
                        estado=0;
                    }
                    else if(texto[contador]== 123){
                        estado=0;
                    }
                    else if(texto[contador]== 125){
                        estado=0;
                    }
                    else if(texto[contador]== 34){
                        estado=5;
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "El simbolo "+texto[contador]+" no pertenece al lenguaje.");
                        errores++;
                    }
                    
                    
                break;
                //confirmar caracter
                case 1:
                    //comentarios
                    if(texto[contador]== 47 ){
                        estado=2;
                    }
                break;
                
                //ignora hasta que encuentre un salto de linea
                case 2:
                    if(texto[contador]==10){
                        //si es salto de linea
                        estado=0;
                        contador--;
                    }else{
                        estado=2;
                    }
                break;
                
                case 3:
                    if(Character.isLetter(texto[contador])){
                        estado = 3;
                    }else{
                        estado = 0;
                        contador--;
                    }
                break;
                
                case 4:
                    if(Character.isDigit(texto[contador])){
                        estado = 4;
                    }else{
                        estado = 0;
                        contador--;
                    }
                break;
                
                case 5:
                    if(texto[contador] == 34){
                        estado =0;
                    }else{
                        //va a aceptar cualquier cosa
                    }
                break;
                
                default:
                    throw new AssertionError();
            }
        }
        
        if(errores ==0){
            JOptionPane.showMessageDialog(rootPane, "Analisis lexico exitoso");
        }else{
            JOptionPane.showMessageDialog(null, "Analisis lexico erroneo", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
